name: Link Check
on:
  pull_request:
    branches: [main]

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress "./README.md" "./content/**/*.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
